### ISSUE TITLE
How do you use this?

### ISSUE THREAD

**Issue by till** [ansible-collections/grafana#25]
##### SUMMARY

How do you use this collection? I noticed there was a discussion in another PR, has this been cleared up? I am happy to send a PR to get this started. 

##### ISSUE TYPE
- Documentation Report

**Comment by rrey** [comment]
Hi @till !
I think we could publish a first version of the collection to have people interested playing with it.
We need to setup the CI to build the collection and publish on a tag creation.

Are you familiar we collections ? Any help is welcome, there are a lot to do around tests and few reworks.

**Comment by till** [comment]
Not really. Or not yet.

**Comment by gundalow** [comment]
Hi @till. thank you for your interest.

## Background on Collections

In the next release of Ansible most (read just about all) modules and plugins will be moved into separate GitHub repositories, which contain **Collections**. This will allow the Collections to be released independently of ansible/ansible, which has been on a twice-yearly release cycle. One of the main objectives is that we can get new module functionality into the hands of end-users much quicker.

github.com/ansible/ansible will be stripped down to just the Ansible Engine and enough modules to bootstrap the rest of the content. See the [use-cases](https://github.com/ansible-community/collection_migration/tree/master/scenarios/minimal) for ansible-minimal, and the current [Work In Progress definition of modules and plugins that remain in ansible/ansible](https://github.com/ansible-community/collection_migration/blob/master/scenarios/minimal/ansible.yml).

Starting with Ansible 2.10 there is a difference between:
* contained in ansible/ansible
* shipped in the Ansible Community distribution

**In Ansible 2.9** you do `$package_manager install ansible` which gives you the Ansible Engine and thousands of modules & plugins. All of this comes from github.com/ansible/ansible


**In Ansible 2.10** when you install the Community version of Ansible (ie not [Red Hat Ansible Automation Platform](https://www.ansible.com/products/automation-platform) you will still get all of the modules. It just happens that when the package (pip, deb, rpm) is built we will pull in the current stable versions of each of the selected community Collections [1].

Since the vast majority of people will go for the "install the kitchen sink" route they will still get the modules, therefore no deprecation cycle is needed


Once the Collection is up and running, the *plan* (i.e. not fully signed off yet) is at that point you can `git rm` the migrated content from ansible/ansible:devel. It's up to you what you want to do with PRs (close or migrate them for people) to the new GitHub repo containing the Collection

Also once the Collection is up and running I'm OK with zero further changes being made to ansible/ansible:devel, ie all feature work can go straight into foreman-ansible-modules. Important bug fixes for Ansible 2.9 can still be made, this is done by raising a PR directly against `stable-2.9` (no longer a backport)



## Grafana

The Grafana Community has very kindly offered to help me (a member of the Community Team at Ansible) use their modules to prototype this new Collection workflow.
Grafana is a very good use-case as there are frequent major API updates to Grafana, whichAnsible with its 6-monthly release cycle often lags behind.

In January we will get Grafana published to https://galaxy.ansible.com/community, (which is currently empty)

We have essentially frozen Grafana in github/ansible/ansible now, and all development is taking place in this new repo.

All the Grafana specific PRs from ansible/ansible have been recreated in this repo.

Though we still need to pull the Grafana specific changes out of https://github.com/ansible/ansible/pull/60051 and raise them in this repo. Is that something that might interest @till ?


Please do shout out if you have further questions, or feel free to DM me on IRC.

Once again, thank you for your interest and support.

**Comment by till** [comment]
I don't understand the history on this PR you mentioned. I am mostly fixing what we need to keep moving at work. Sorry to be a little selfish, but we're a small team and I am not dedicated to this. It's more a drive-by thing for me. ;) I'll contribute where I can though.

---

Starting with which Ansible version do I need to add collections to my `requirements.yml`? I think that may be the most important part to understand. And I haven't seen that yet anywhere.

I just read [the docs on collections](https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-collections-with-ansible-galaxy) and the overall intend makes sense^W^W^sounds great. E.g. not waiting for Ansible releases to get fixes and new features.

I am not entirely sure how it works though. Would that mean, I install Ansible through e.g. `pip`, then install the collections via `ansible-galaxy`? I am not entirely sure what the "kitchen sink approach" means. Is that the package manager of my distro?

---

LBNL, my concern is that Galaxy doesn't seem to be up to serving all that additional traffic. E.g. see the ticket I opened @ ansible/galaxy#2170 and then it took nudging on IRC (btw, thank you for your help!) to get any traction on it.

E.g. it was broken for over 24 hours, not sure how this is gonna fly with all the new traffic and people depending on it even more. Is there anything else to address that in the works? All of this seems to be a side project for IBM RH?

**Comment by till** [comment]
Also, if I was to start using this now, how does this play with the modules included *in* Ansible currently? Is that a show-stopper?

**Comment by rrey** [comment]
This repository contains the same Grafana modules as the one currently in Ansible.
We recently created a Working Group around Grafana, so we will try to factorize some code and improve things that can be improved.

So what is on master right now should behave the same way as the modules on ansible 2.9.
If you have roles and playbook using the Ansible modules, you should be able to move to the collection without changing anything (hopefully).

I'll try to get a first release in coming days, and add a Readme section to get started with the collection. If you are interested, you could review it and tell me if something was missing.

**Comment by Altiire** [comment]
Hi,
I'm back with the main question "How do you use this?"
I enabled the callback in ansible.cfg
```
callback_whitelist = ansible_community.grafana.grafana_annotations
```
And configured it at the bottom of the ansible.cfg file
```
[callback_grafana_annotations]
grafana_url = myurl
grafana_api_key = mykey
```
But i get the following error: ` [ERROR]: Could not submit message to Grafana: 'CallbackModule' object has no attribute 'grafana_url'`
I don't get what I'm missing...

**Comment by rrey** [comment]
It could be a bug, I did not test the callback on 2.9
Did you try with environment variables ? It will exclude the Ansible.cfg use for configuration.

**Comment by Altiire** [comment]
@rrey Ok thank you, I will use the callback bundled in ansible for now

**Comment by rrey** [comment]
If that's ok for you guys I'll close this issue.
